# Use a lightweight nginx image
FROM nginx:alpine

# Copy the HTML, CSS, and JS files to the appropriate location in the container
COPY . /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]
